[package]
name = "rust-kr"
version = "0.1.1"
authors = ["Hyeon Kim <simnalamburt@gmail.com>"]
edition = "2018"

[dependencies]
iron = "0.6"
router = "0.6"
staticfile = "0.5"
handlebars-iron = "0.27"
pulldown-cmark = "0.1.0"
